### PR TITLE
Fix critical vulnerability CWE-78 

### PR DESCRIPTION
**Pull request by JamesCodes**
I have simply fixed the linting errors in the PR raised by @Narvey

https://github.com/postcss/postcss-filter-plugins/pull/18

### CODE REVIEW

**Comment by RyanZim** [comment]
I repeat:
> why do we need a UUID function; wouldn't just a plain old `Math.random().toString()` work?

**Comment by JamesCodes** [comment]
@RyanZim Repeat noted. If that provides the same solution and doesn't cause any issues, I'm with you. I was under the impression that the unique lib was being used to reduce the chance of two random strings ending up being the same.

But you may very well be right, `Math.random().toString()` may achieve that just fine.

**Comment by RyanZim** [comment]
We're talking about giving each plugin an id; most plugin chains aren't crazy long, I don't think the uniqueness will be an issue.

**Comment by JamesCodes** [comment]
@RyanZim Yeah, that makes sense.

**Comment by RyanZim** [comment]
Also, should have mentioned this the first time; please remove `package-lock.json` from git.

**Comment by JamesCodes** [comment]
@RyanZim I've made those changes.

**Comment by RyanZim** [comment]
Thanks!

**Comment by RyanZim** [comment]
Feel free to add yourself here if you'd like: https://github.com/postcss/postcss-filter-plugins#contributors

**Comment by JamesCodes** [comment]
Will do 👍

**Pull request merged**
