### PR TITLE
CWE-78 fix for v2

### PR DESCRIPTION
**Pull request by rettgerst**
I use a package (css-loader) which indirectly depends on v2 of postcss-filter-plugins, so porting the cwe-78 fix to the older version would fix the audit warnings for myself and the many other people who use css-loader, or current versions of cssnano.

I literally just cherry-picked the changes from 3.0.1 onto 2.0.2.

(looks like y'all don't have a branch for v2, and I guess github doesn't have a way to suggest creating a new branch in the base repository? strange.)

### CODE REVIEW

**Comment by alexander-akait** [comment]
@rettgerst please solve merge problem

**Comment by RyanZim** [comment]
This is based on an older version of `master`, so merge problems are OK and expected. I need to manually merge.

**Comment by alexander-akait** [comment]
@RyanZim can we wait release in near future?

**Comment by RyanZim** [comment]
Cherry-picked to https://github.com/postcss/postcss-filter-plugins/tree/2.x.x and released as 2.0.3. :tada: 

Please consider upgrading to PostCSS v6 and postcss-filter-plugins v3 if possible.

**Comment by rettgerst** [comment]
~~can you publish it to npm? [doesn't look like it's up yet](https://www.npmjs.com/package/postcss-filter-plugins)~~

nevermind, looks like this is [npm's problem](https://status.npmjs.org/incidents/3rjzvts6v98k)

**Comment by alexander-akait** [comment]
@rettgerst looks `npm` have some problems, i can't publish own package too, just wait

**Pull request closed without merging**
