### PR TITLE
Switch to Babel 7 for build

### PR DESCRIPTION
**Pull request by pravi**
Use Babel 7 for transpiling instead of babel 6

### CODE REVIEW

**Comment by pravi** [comment]
Though it means we have to drop support for nodejs 4 and 6 (tests passed for Node 8 and 9).

**Comment by pravi** [comment]
Or even better remove babel like other postcss modules have done. For example https://github.com/css-modules/postcss-modules-extract-imports/commit/797d678bcc6cc7e07dbbc8323b3e9eec8e68b805

**Comment by RyanZim** [comment]
Yeah, if we're gonna change anything, I'd sooner drop babel. Is there a compelling reason to make any changes here, though? The plugin works as-is.

**Comment by pravi** [comment]
@RyanZim we prefer to maintain only one version of Babel in Debian and we have already patched postcss-filter-plugins in debian to build with Babel 7. But it'd be nice to stay close to the versions that you use so we can reproduce problems easily.

**Comment by pravi** [comment]
and in Debian main we have to build everything from source using the tools available in Debian main.

**Comment by RyanZim** [comment]
What kind of weird setup are you using? Installing npm modules from Debian repositories? Just use npm or yarn, please.

**Comment by pravi** [comment]
If you don't want to update that is fine. There is nothing weird in using native Debian packages, only node module authers want to force their preferred package manager on others. Every other software in the world works just fine with apt. There is nothing wrong in wanting to build a software from its source code or wanting to use recent versions of a build tool.

**Comment by pravi** [comment]
There are also some exceptions like this https://gitlab.com/rhendric/puka/-/issues/1 who are considerate about downstream packages.

**Comment by RyanZim** [comment]
Node is fundamentally not built to work with apt, we're not going to support that here.

**Comment by pravi** [comment]
If you don't want to support, that is fair enough. But fortunately node and the module you wrote are Free Software, which means you don't get to force your choices on me or others.

**Comment by RyanZim** [comment]
Yep, that's the beauty of open source. :+1: Good luck

**Pull request closed without merging**
